// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Family struct {
	ID        uuid.UUID
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type FamilyMember struct {
	ID        uuid.UUID
	FamilyID  uuid.UUID
	UserID    uuid.UUID
	Role      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Gift struct {
	ID          uuid.UUID
	FamilyID    uuid.UUID
	HolidayID   uuid.NullUUID
	RecipientID uuid.UUID
	CreatorID   uuid.UUID
	Name        string
	Description sql.NullString
	Price       sql.NullString
	Url         sql.NullString
	Status      string
	ReservedBy  uuid.NullUUID
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type GiftPreference struct {
	ID             uuid.UUID
	FamilyMemberID uuid.UUID
	Category       string
	PreferenceType string
	Details        sql.NullString
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type Holiday struct {
	ID        uuid.UUID
	FamilyID  uuid.UUID
	Name      string
	Date      time.Time
	Recurring sql.NullBool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID        uuid.UUID
	Auth0ID   string
	Email     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
